<!-- frontend/src/routes/organizations/[id]/+page.svelte -->
<script lang="ts">
	// domainsApi is no longer needed here for adding domains
	import { page } from '$app/stores';
	import type { PageData } from './$types'; // Generated by SvelteKit
	import type { RootDomain, ScanTemplate } from '$lib/types'; // Added ScanTemplate
	import AlertMessage from '$lib/components/AlertMessage.svelte';
	import AddDomainForm from '$lib/components/AddDomainForm.svelte'; // Import the form component
	import Modal from '$lib/components/Modal.svelte'; // Import Modal component
	import { onMount } from 'svelte';
	import { scanTemplatesApi } from '$lib/api/api'; // Import scanTemplatesApi

	export let data: PageData; // Data loaded from +page.ts

	let organization: PageData['organization'];
	let domains: RootDomain[] = [];
	let showScanTemplateModal = false;
	let selectedDomainId: number | null = null;
	let selectedDomainName: string | null = null;
	let availableScanTemplates: ScanTemplate[] = [];
	let selectedTemplateId: number | null = null;
	let isLoadingTemplates = false;
	let templateError: string | null = null;

	// Reactive statement to update local state when props change
	$: {
		organization = data.organization;
		domains = organization?.root_domains || [];
	}

	// Handler for the 'domainAdded' event from AddDomainForm
	function handleDomainAdded(event: CustomEvent<RootDomain>) {
		const addedDomain = event.detail;
		// Add the new domain to the list and sort
		domains = [...domains, addedDomain].sort((a, b) => a.domain.localeCompare(b.domain));
		// Success message is now handled within AddDomainForm
	}

	// Function to open the modal and fetch templates
	async function openScanModal(domainId: number, domainName: string) {
		selectedDomainId = domainId;
		selectedDomainName = domainName;
		selectedTemplateId = null; // Reset selection
		templateError = null; // Reset error
		showScanTemplateModal = true;
		isLoadingTemplates = true;
		try {
			// Corrected API call
			availableScanTemplates = await scanTemplatesApi.getScanTemplates();
		} catch (err) {
			templateError = `Failed to load scan templates: ${err instanceof Error ? err.message : 'Unknown error'}`;
			availableScanTemplates = []; // Ensure it's empty on error
		} finally {
			isLoadingTemplates = false;
		}
	}

	// Function to trigger a scan using the selected template
	import { domainsApi } from '$lib/api/api'; // Ensure domainsApi is imported
	async function handleScanWithTemplate() {
		if (selectedDomainId === null || selectedDomainName === null || selectedTemplateId === null) {
			alert('Error: Domain or template not selected.');
			return;
		}

		// Optional: Add confirmation if desired
		// if (!confirm(`Start scan for ${selectedDomainName} using selected template?`)) {
		// 	return;
		// }

		try {
			// TODO: Update domainsApi.scanDomain to accept templateId or use a different endpoint
			// Assuming scanDomain needs modification or a new method exists like scanDomainWithTemplate(domainId, templateId)
			// For now, let's simulate the call and show an alert. Replace with actual API call.
			console.log(`Scanning domain ${selectedDomainId} (${selectedDomainName}) with template ${selectedTemplateId}`);
			// const result = await domainsApi.scanDomainWithTemplate(selectedDomainId, selectedTemplateId); // Example future API call
			// alert(`Scan started for ${selectedDomainName} using template. Scan ID: simulated_id`); // Replace with result.scan_id

			// TEMPORARY: Use existing scanDomain until API is updated
			alert(`Note: Scan template selection is not yet fully integrated with the backend.\nStarting default scan for ${selectedDomainName}.`);
			const result = await domainsApi.scanDomain(selectedDomainId);
			alert(`Default scan started for ${selectedDomainName}. Scan ID: ${result.scan_id}`);


			closeModal(); // Close modal on success
		} catch (err) {
			alert(`Failed to start scan: ${err instanceof Error ? err.message : 'Unknown error'}`);
			// Optionally keep modal open on error?
		}
	}

	function closeModal() {
		showScanTemplateModal = false;
		selectedDomainId = null;
		selectedDomainName = null;
		selectedTemplateId = null;
		templateError = null;
	}

</script>

<svelte:head>
	<title>Organization: {organization?.name || 'Loading...'}</title>
</svelte:head>

<div class="organization-detail">
	{#if organization}
		<h1 class="text-2xl font-bold mb-4">Organization: {organization.name}</h1>
		<p class="text-sm text-gray-400 mb-4">Created: {new Date(organization.created_at).toLocaleDateString()}</p>

		<!-- Stats Section -->
		<div class="stats grid grid-cols-3 gap-4 mb-6 p-4 bg-gray-800 rounded border border-gray-700">
			<div class="stat text-center">
				<div class="stat-value text-2xl font-bold">{organization.total_root_domains ?? 0}</div>
				<div class="stat-title text-sm text-gray-400">Root Domains</div>
			</div>
			<div class="stat text-center">
				<div class="stat-value text-2xl font-bold">{organization.total_subdomains ?? 0}</div>
				<div class="stat-title text-sm text-gray-400">Subdomains</div>
			</div>
			<div class="stat text-center">
				<div class="stat-value text-2xl font-bold">{organization.total_endpoints ?? 0}</div>
				<div class="stat-title text-sm text-gray-400">Endpoints</div>
			</div>
		</div>

		{#if organization.notes}
			<div class="mb-4">
				<h3 class="text-md font-semibold mb-1">Notes:</h3>
				<p class="text-sm whitespace-pre-wrap">{organization.notes}</p>
			</div>
		{/if}

		{#if organization.bug_bounty_link}
			<div class="mb-6">
				<h3 class="text-md font-semibold mb-1">Bug Bounty Program:</h3>
				<a href={organization.bug_bounty_link} target="_blank" rel="noopener noreferrer" class="text-blue-400 hover:underline break-all">
					{organization.bug_bounty_link}
				</a>
			</div>
		{/if}

		<section class="add-domain mb-8">
			<h2 class="text-xl font-semibold mb-3">Add New Domain to {organization.name}</h2>
			<!-- Use the AddDomainForm component -->
			<AddDomainForm 
				organizationId={organization.id} 
				on:domainAdded={handleDomainAdded} 
			/>
			<!-- Error/Success messages are now handled inside AddDomainForm -->
			<!-- Error/Success messages are now handled inside AddDomainForm -->
		</section>

		<!-- Add Import Link/Button Here -->
		<div class="mb-8 text-right">
			<a href={`/organizations/${organization.id}/import`} class="btn btn-primary">
				Import Data (URLs/Subdomains)
			</a>
		</div>

		<section class="monitored-domains">
			<h2 class="text-xl font-semibold mb-3">Monitored Domains ({domains.length})</h2>
			{#if domains.length === 0}
				<p class="text-gray-500 italic">No domains added to this organization yet.</p>
			{:else}
				<div class="domain-list space-y-2">
					{#each domains as domain (domain.id)}
						<div class="domain-item flex justify-between items-center p-3 bg-gray-800 rounded border border-gray-700">
							<a href={`/domains/${domain.id}`} class="text-blue-400 hover:underline">{domain.domain}</a>
							<button
								class="btn btn-secondary btn-sm"
								on:click={() => openScanModal(domain.id, domain.domain)}
							>
								Scan...
							</button>
						</div>
					{/each}
				</div>
			{/if}
		</section>

	<!-- Remove the {:else if error} block for load errors, SvelteKit handles this -->
	{:else}
		<h1 class="text-2xl font-bold mb-4">Loading Organization...</h1>
		<p>Please wait...</p>
	{/if}
</div>

<!-- Scan Template Selection Modal -->
<Modal bind:show={showScanTemplateModal} on:close={closeModal}>
	<h2 class="text-xl font-semibold mb-4">Select Scan Template for {selectedDomainName}</h2>

	{#if isLoadingTemplates}
		<p>Loading templates...</p>
	{:else if templateError}
		<AlertMessage type="error" message={templateError} />
	{:else if availableScanTemplates.length === 0}
		<p>No scan templates found. You can create them in the Scan Templates section.</p>
		<div class="mt-4 text-right">
			<button class="btn btn-secondary" on:click={closeModal}>Cancel</button>
		</div>
	{:else}
		<div class="template-list space-y-2 mb-4 max-h-60 overflow-y-auto">
			{#each availableScanTemplates as template (template.id)}
				<label class="flex items-center p-2 rounded hover:bg-gray-700 cursor-pointer border border-transparent has-[:checked]:border-blue-500 has-[:checked]:bg-gray-700">
					<input type="radio" name="scan-template" value={template.id} bind:group={selectedTemplateId} class="mr-2 radio radio-primary radio-sm" />
					<!-- Removed non-existent module_name -->
					<span>{template.name}</span> 
				</label>
			{/each}
		</div>
		<div class="modal-actions text-right space-x-2">
			<button class="btn btn-secondary" on:click={closeModal}>Cancel</button>
			<button class="btn btn-primary" on:click={handleScanWithTemplate} disabled={selectedTemplateId === null}>
				Start Scan
			</button>
		</div>
	{/if}
</Modal>


<style>
	/* Add specific styles if needed, rely on Tailwind/global styles */
	.domain-item {
		background-color: var(--card-bg);
		border-color: var(--border);
	}
	.btn-sm {
		padding: 0.25rem 0.5rem;
		font-size: 0.875rem;
	}
</style>
